/**
 * 表单检测和填充相关常量配置
 * 集中管理所有魔法数字，提高可维护性
 *
 * @author Link Pilot Team
 * @date 2026-03-13
 */

/**
 * 表单检测配置常量
 */
export const FORM_DETECTION_CONFIG = {
  // 标签距离阈值（像素）
  LABEL_DISTANCE_THRESHOLD_TOP: 100,
  LABEL_DISTANCE_THRESHOLD_LEFT: 200,
  LABEL_HORIZONTAL_DISTANCE_MAX: 50,

  // Shadow DOM 配置
  SHADOW_DOM_MAX_DEPTH: 10,

  // 字段质量阈值
  FIELD_QUALITY_THRESHOLD: 0.4,
  MIN_FIELD_QUALITY: 0.3,

  // 性能配置
  PERFORMANCE_WARNING_THRESHOLD: 1000, // 毫秒

  // 缓存配置
  CACHE_MAX_SIZE: 100,
  CACHE_TTL_MS: 5 * 60 * 1000, // 5分钟

  // 防抖/节流配置
  DEBOUNCE_DELAY: 500, // 毫秒
  THROTTLE_DELAY: 1000, // 毫秒

  // 填充策略配置
  HUMAN_TYPING_DELAY_MIN: 30, // 毫秒
  HUMAN_TYPING_DELAY_MAX: 50, // 毫秒
  FILL_TIMEOUT: 10000, // 10秒

  // 正则表达式安全限制
  REGEX_MAX_LENGTH: 200,
  REGEX_MAX_WILDCARDS: 5,

  // 位置检测配置
  POSITIONAL_LABEL_CHECK_MARGIN: 5, // 像素
  POSITIONAL_LABEL_MAX_CANDIDATES: 20,
  POSITIONAL_LABEL_CONTAINER_MAX_DEPTH: 3,
  POSITIONAL_LABEL_MIN_TEXT_LENGTH: 2,
  POSITIONAL_LABEL_MIN_TEXT_LENGTH_TOP: 3,

  // 文本清理配置
  MAX_LABEL_TEXT_LENGTH: 200,

  // 字段质量评分权重
  QUALITY_SCORE_LABEL_TAG: 0.3,
  QUALITY_SCORE_POSITIONAL_LABEL: 0.2,
  QUALITY_SCORE_PLACEHOLDER: 0.1,
  QUALITY_SCORE_VISIBLE_INTERACTIVE: 0.2,
  QUALITY_SCORE_TOP_ELEMENT: 0.2,

  // 字段置信度权重
  CONFIDENCE_WEIGHT_COMMENT: 0.4,
  CONFIDENCE_WEIGHT_EMAIL: 0.2,
  CONFIDENCE_WEIGHT_NAME: 0.2,
  CONFIDENCE_WEIGHT_WEBSITE: 0.1,
  CONFIDENCE_WEIGHT_SUBMIT: 0.1,

  // 字段置信度提升值
  CONFIDENCE_BOOST_NAME_MATCH: 0.25,
  CONFIDENCE_BOOST_ID_MATCH: 0.15,
  CONFIDENCE_BOOST_PLACEHOLDER_MATCH: 0.1,
  CONFIDENCE_BOOST_TYPE_MATCH: 0.2,
  CONFIDENCE_BASE: 0.5,

  // 选择器生成配置
  SELECTOR_MAX_PATH_DEPTH: 4,
  SELECTOR_MAX_CLASSES: 2,

  // 回退检测配置
  MIN_FIELDS_FOR_HEURISTIC: 2,
} as const;
