/**
 * comment-generator.ts
 * 评论生成器工具函数
 * @author Link Pilot Team
 * @date 2026-03-13
 */

import type { FillPageState, ManagedBacklink, WebsiteProfile } from '../types/models.js';

const DEFAULT_COMMENT_TEMPLATES = [
  '感谢分享，关于 {pageTopic} 的内容整理得很清晰。',
  '这篇内容对理解 {pageTopic} 很有帮助，尤其是 {pageFocus} 这一部分。',
  '刚读完 {pageTitle}，信息梳理得很完整，也让我重新梳理了 {pageTopic}。',
];

const PLACEHOLDER_PATTERN = /\{([a-zA-Z0-9_]+)\}/g;

function normalizeText(value?: string | null): string {
  return (value ?? '').replace(/\s+/g, ' ').trim();
}

function truncateText(value: string, maxLength: number): string {
  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, Math.max(0, maxLength - 1)).trim()}...`;
}

function parseDomain(value?: string): string {
  if (!value) {
    return '';
  }

  try {
    return new URL(value).hostname.replace(/^www\./, '');
  } catch {
    return value.replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0] ?? '';
  }
}

function dedupeComments(comments: string[]): string[] {
  const seen = new Set<string>();

  return comments.filter(comment => {
    const normalized = normalizeText(comment);
    if (!normalized || seen.has(normalized)) {
      return false;
    }

    seen.add(normalized);
    return true;
  });
}

function interpolateTemplate(template: string, values: Record<string, string>): string {
  return template.replace(PLACEHOLDER_PATTERN, (_match, key: string) => values[key] ?? '');
}

function buildContextTail(values: Record<string, string>): string {
  const topic = values.pageTopic || values.pageDomain || '当前主题';
  const title = values.pageTitle ? `《${values.pageTitle}》` : '';
  const focus = values.pageDescription || values.pageH1 || values.backlinkNote;

  const parts = [
    title ? `这篇 ${title} 围绕 ${topic} 的信息整理得很顺。` : `这篇关于 ${topic} 的内容读起来很顺畅。`,
    focus ? `尤其是 ${truncateText(focus, 42)} 这部分，很有参考价值。` : '',
    values.backlinkKeywords ? `和 ${values.backlinkKeywords} 这些方向也比较契合。` : '',
  ].filter(Boolean);

  return parts.join(' ');
}

export function buildCommentCandidates(
  profile: WebsiteProfile,
  pageState: FillPageState | null,
  currentBacklink: ManagedBacklink | null,
): string[] {
  // 输入验证
  if (!profile) {
    throw new Error('profile 参数不能为空');
  }

  if (!profile.name || typeof profile.name !== 'string') {
    throw new Error('profile.name 必须是非空字符串');
  }

  if (profile.name.trim().length === 0) {
    throw new Error('profile.name 不能为空白字符串');
  }

  // 验证 pageState（如果提供）
  if (pageState !== null && typeof pageState !== 'object') {
    throw new Error('pageState 必须是对象或 null');
  }

  // 验证 currentBacklink（如果提供）
  if (currentBacklink !== null && typeof currentBacklink !== 'object') {
    throw new Error('currentBacklink 必须是对象或 null');
  }

  const pageTitle = normalizeText(pageState?.seo.title);
  const pageH1 = normalizeText(pageState?.seo.h1);
  const pageDescription = normalizeText(pageState?.seo.description);
  const pageUrl = normalizeText(pageState?.seo.url);
  const pageDomain = parseDomain(pageUrl);
  const pageTopic = truncateText(pageH1 || pageTitle || pageDomain || '当前主题', 72);
  const pageFocus = truncateText(pageDescription || pageH1 || pageTitle || pageTopic, 72);
  const backlinkNote = normalizeText(currentBacklink?.note);
  const backlinkKeywords = (currentBacklink?.keywords ?? []).map(keyword => normalizeText(keyword)).filter(Boolean).slice(0, 3).join('、');
  const values = {
    websiteName: normalizeText(profile.name),
    websiteUrl: normalizeText(profile.url),
    websiteDomain: normalizeText(profile.domain) || parseDomain(profile.url),
    email: normalizeText(profile.email),
    pageTitle,
    pageH1,
    pageDescription,
    pageUrl,
    pageDomain,
    pageTopic,
    pageFocus,
    backlinkNote,
    backlinkKeywords,
  };

  const baseTemplates = profile.comments.map(comment => normalizeText(comment)).filter(Boolean);
  const sourceTemplates = baseTemplates.length > 0 ? baseTemplates : DEFAULT_COMMENT_TEMPLATES;
  const contextTail = buildContextTail(values);

  const generatedFromTemplates = sourceTemplates.map(template => {
    const interpolated = normalizeText(interpolateTemplate(template, values));
    if (!interpolated) {
      return '';
    }

    const hasPlaceholders = PLACEHOLDER_PATTERN.test(template);
    PLACEHOLDER_PATTERN.lastIndex = 0;

    if (hasPlaceholders || !contextTail) {
      return interpolated;
    }

    return normalizeText(`${interpolated} ${contextTail}`);
  });

  const autoGenerated = DEFAULT_COMMENT_TEMPLATES.map(template => normalizeText(interpolateTemplate(template, values)));

  return dedupeComments([...generatedFromTemplates, ...autoGenerated]).slice(0, 8);
}
